#!/usr/bin/env bash

if [ -d out ]; then
	find out/ -maxdepth 1 -mindepth 1 -exec rm -rf {} \;
fi

export DEBUG="*,-mquery,-data/connection,-babel,-agenda*"

clear
echo -en "Building The App\n"

cp src/tsconfig.json out/tsconfig.json
cp .env out/.env
cp -R ssl out/ssl

node_modules/.bin/tsc --pretty --project src/tsconfig.json
